name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15.5"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run vetting
        run: |
          cd $GITHUB_WORKSPACE
          export PATH=$PATH:$(go env GOPATH)/bin
          cd $GITHUB_WORKSPACE
          go vet ./...
      - name: Run linting
        run: |
          cd $GITHUB_WORKSPACE
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u golang.org/x/lint/golint
          go vet ./...
          golint ./...
      - name: Run tests
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          CI: true
        run: |
          cd $GITHUB_WORKSPACE
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u github.com/mattn/goveralls
          go test --cover --coverprofile pack.coverprofile
          goveralls -coverprofile=pack.coverprofile -repotoken $COVERALLS_TOKEN
